package org.papiricoh.supernaturalcraft.author;

import com.mojang.serialization.MapCodec;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.Registries;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.levelgen.Heightmap;
import net.minecraft.world.level.levelgen.structure.Structure;
import net.minecraft.world.level.levelgen.structure.StructureType;
import org.papiricoh.supernaturalcraft.SupernaturalCraft;
import org.papiricoh.supernaturalcraft.registry.AllStructures;

import java.util.Optional;

/**
 * The Author's cabin: small, alone, far from everything; one per world. Of the {@link CabinSite} candidates, the
 * first whose ground is quiet (a forest, plains, meadow… on flat dry land) holds it, or the last if none is
 * ({@link AuthorSite#chosen}); the other candidates generate nothing.
 */
public class AuthorCabinStructure extends Structure {

    public static final MapCodec<AuthorCabinStructure> CODEC = simpleCodec(AuthorCabinStructure::new);
    /** The quiet biomes a cabin may stand in (generated by datagen: forests, plains, meadows, taiga, cherry groves…). */
    public static final TagKey<Biome> QUIET_BIOMES = TagKey.create(Registries.BIOME, SupernaturalCraft.asResource("author_cabin_biomes"));

    public AuthorCabinStructure(StructureSettings settings) {
        super(settings);
    }

    @Override
    protected Optional<GenerationStub> findGenerationPoint(GenerationContext ctx) {
        ChunkPos cp = ctx.chunkPos();
        int k = CabinSite.indexOf(AuthorPlacement.candidates(ctx.seed()), cp.x, cp.z);
        if (k < 0) return Optional.empty();
        if (AuthorSite.chosen(ctx.seed(), ctx.chunkGenerator(), ctx.biomeSource(), ctx.randomState(), ctx.heightAccessor()) != k) {
            return Optional.empty();
        }
        int x = cp.getMiddleBlockX(), z = cp.getMiddleBlockZ();
        int y = ctx.chunkGenerator().getBaseHeight(x, z, Heightmap.Types.WORLD_SURFACE_WG, ctx.heightAccessor(), ctx.randomState());
        BlockPos origin = new BlockPos(x, y, z);
        int turn = CabinSite.rotation(ctx.seed());
        return Optional.of(new GenerationStub(origin, builder -> builder.addPiece(new CabinPiece(origin, turn))));
    }

    @Override
    public StructureType<?> type() {
        return AllStructures.AUTHOR_CABIN.get();
    }
}
