package org.papiricoh.supernaturalcraft.crossroads.wild;

import com.mojang.serialization.MapCodec;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.levelgen.Heightmap;
import net.minecraft.world.level.levelgen.structure.Structure;
import net.minecraft.world.level.levelgen.structure.StructureSet;
import net.minecraft.world.level.levelgen.structure.StructureType;
import org.papiricoh.supernaturalcraft.SNConfig;
import org.papiricoh.supernaturalcraft.SupernaturalCraft;
import org.papiricoh.supernaturalcraft.registry.AllStructures;

import java.util.Optional;

/**
 * A natural crossroads (v0.18): two old dirt roads crossing in open country, a signpost, a dead tree, and at the very centre the
 * trodden earth where a crossroads box can be buried. Finding the spot costs ten height samples (the grave's pattern: this runs
 * for {@code /locate} and maps too) judged by the pure {@link CrossroadsLayout#suitable}; the rest is planned by
 * {@link CrossroadsLayout#plan} when it is built ({@link CrossroadsPiece}, {@link CrossroadsBuilder}). Off with the
 * {@code crossroadsWild.enabled} server config.
 */
public class CrossroadsStructure extends Structure {

    public static final MapCodec<CrossroadsStructure> CODEC = simpleCodec(CrossroadsStructure::new);
    public static final ResourceKey<Structure> KEY = ResourceKey.create(Registries.STRUCTURE, SupernaturalCraft.asResource("crossroads"));
    public static final ResourceKey<StructureSet> SET = ResourceKey.create(Registries.STRUCTURE_SET, SupernaturalCraft.asResource("crossroads"));
    /** Biomes natural crossroads are found in (generated by datagen). */
    public static final TagKey<Biome> BIOMES = TagKey.create(Registries.BIOME, SupernaturalCraft.asResource("has_structure/crossroads"));
    /** Placement: about one per {@code SPACING} x {@code SPACING} chunks, never closer than {@code SEPARATION}. */
    public static final int SPACING = 36, SEPARATION = 14, SALT = 0x0C40_55AD;
    /** The corners sampled around the centre: the roads' near reach, where they must lie flat and dry. */
    private static final int REACH = 10;

    public CrossroadsStructure(StructureSettings settings) {
        super(settings);
    }

    @Override
    protected Optional<GenerationStub> findGenerationPoint(GenerationContext ctx) {
        if (SNConfig.SPEC.isLoaded() && !SNConfig.WILD_CROSSROADS.get()) return Optional.empty();
        ChunkPos cp = ctx.chunkPos();
        int x = cp.getMiddleBlockX(), z = cp.getMiddleBlockZ();
        int[][] at = {{0, 0}, {-REACH, -REACH}, {REACH, -REACH}, {-REACH, REACH}, {REACH, REACH}};
        int[] tops = new int[at.length], floors = new int[at.length];
        for (int i = 0; i < at.length; i++) {
            tops[i] = height(ctx, x + at[i][0], z + at[i][1], Heightmap.Types.WORLD_SURFACE_WG);
            floors[i] = height(ctx, x + at[i][0], z + at[i][1], Heightmap.Types.OCEAN_FLOOR_WG);
        }
        if (!CrossroadsLayout.suitable(tops, floors, ctx.chunkGenerator().getSeaLevel())) return Optional.empty();
        BlockPos origin = new BlockPos(x, tops[0] + 1, z);
        long seed = ctx.seed() ^ cp.toLong() * 0x9E3779B97F4A7C15L ^ SALT;
        int dir = CrossroadsBuilder.dirOf(seed);
        return Optional.of(new GenerationStub(origin, builder -> builder.addPiece(new CrossroadsPiece(origin, dir, seed))));
    }

    private static int height(GenerationContext ctx, int x, int z, Heightmap.Types type) {
        return ctx.chunkGenerator().getBaseHeight(x, z, type, ctx.heightAccessor(), ctx.randomState()) - 1;
    }

    @Override
    public StructureType<?> type() {
        return AllStructures.CROSSROADS.get();
    }
}
