package org.papiricoh.supernaturalcraft.grave;

import com.mojang.serialization.MapCodec;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.Registries;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.levelgen.Heightmap;
import net.minecraft.world.level.levelgen.structure.Structure;
import net.minecraft.world.level.levelgen.structure.StructureType;
import org.papiricoh.supernaturalcraft.SupernaturalCraft;
import org.papiricoh.supernaturalcraft.registry.AllStructures;

import java.util.Optional;

/**
 * A lonely graveyard on flat, dry land: one to three graves, one of them restless. Finding the
 * spot costs ten height samples (this runs for {@code /locate} and maps too); the rest is planned
 * by {@link GraveLayout} when it is actually built.
 */
public class GraveStructure extends Structure {

    public static final MapCodec<GraveStructure> CODEC = simpleCodec(GraveStructure::new);
    /** Biomes graves are dug in (generated by datagen: plains, forests, taiga, meadow, swamp). */
    public static final TagKey<Biome> BIOMES = TagKey.create(Registries.BIOME, SupernaturalCraft.asResource("has_structure/grave"));
    /** The corners sampled around the centre. */
    private static final int REACH = 6;

    public GraveStructure(StructureSettings settings) {
        super(settings);
    }

    @Override
    protected Optional<GenerationStub> findGenerationPoint(GenerationContext ctx) {
        ChunkPos cp = ctx.chunkPos();
        int x = cp.getMiddleBlockX(), z = cp.getMiddleBlockZ();
        int[][] at = {{0, 0}, {-REACH, -REACH}, {REACH, -REACH}, {-REACH, REACH}, {REACH, REACH}};
        int[] tops = new int[at.length], floors = new int[at.length];
        for (int i = 0; i < at.length; i++) {
            tops[i] = height(ctx, x + at[i][0], z + at[i][1], Heightmap.Types.WORLD_SURFACE_WG);
            floors[i] = height(ctx, x + at[i][0], z + at[i][1], Heightmap.Types.OCEAN_FLOOR_WG);
        }
        if (!GraveLayout.suitable(tops, floors, ctx.chunkGenerator().getSeaLevel())) return Optional.empty();
        BlockPos ground = new BlockPos(x, tops[0], z);
        long seed = ctx.seed() ^ cp.toLong() * 0x9E3779B97F4A7C15L;
        return Optional.of(new GenerationStub(ground, builder -> builder.addPiece(new GravePiece(GraveLayout.plan(ground, seed)))));
    }

    private static int height(GenerationContext ctx, int x, int z, Heightmap.Types type) {
        return ctx.chunkGenerator().getBaseHeight(x, z, type, ctx.heightAccessor(), ctx.randomState()) - 1;
    }

    @Override
    public StructureType<?> type() {
        return AllStructures.GRAVE.get();
    }
}
