package org.papiricoh.supernaturalcraft.journal;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.mojang.serialization.JsonOps;
import net.minecraft.resources.ResourceLocation;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.papiricoh.supernaturalcraft.crossroads.BossProgression;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.TreeMap;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The Hunter's Journal as generated by {@code runData}: every entry parses, every key it names has
 * its English text, everything it points at exists, and every creature and boss of the mod has its
 * page (the "everything new goes into the journal" rule of CLAUDE.md).
 */
class JournalEntriesTest {

    private static final String NS = "supernaturalcraft";
    private static final Path GENERATED = Path.of("src/generated/resources");
    private static final Path MAIN = Path.of("src/main/resources");
    private static final Path ENTRIES = GENERATED.resolve("assets/" + NS + "/journal/entries");
    private static final Path LANG = GENERATED.resolve("assets/" + NS + "/lang/en_us.json");

    /** Entries other parts of the book link to by id (roadmap nodes, the dashboard). */
    private static final List<String> REQUIRED = List.of(
            "family_business", "salt", "black_eyes", "devils_trap", "grimoire", "holy_water", "rituals", "azazel",
            "key_to_the_cage", "lilith", "last_seal", "lucifer", "the_colt", "lucifers_grace", "hymnal_spire", "broken_chorus",
            "eclipse", "amara", "metatron", "hell", "four_horsemen", "lucifer_uncaged", "spell_bowl", "ghosts", "crossroads",
            "war", "famine", "pestilence", "death");

    /**
     * Every living creature of the mod. ADD EVERY NEW MOB HERE (and give it a bestiary entry with
     * {@code .creature(type)} in {@code datagen/journal}). Projectiles, markers, zones, illusions and
     * the non-living constructs (Metatron's hand and book) are not creatures.
     */
    private static final List<String> CREATURES = List.of(
            "black_eyed_demon", "demon_occultist", "crossroads_demon", "hellhound", "bound_hellhound", "ghost",
            "amara_shade", "choir_echo", "caged_lucifer",
            "azazel", "lilith", "lucifer", "broken_chorus", "metatron", "amara", "lucifer_uncaged", "chuck",
            "war", "famine", "pestilence", "death", "horseman_steed", "hungry_thrall", "fly_swarm", "reaper");

    private static Map<String, JournalEntry> entries;
    private static JsonObject lang;

    @BeforeAll
    static void load() throws IOException {
        assertTrue(Files.isDirectory(ENTRIES), "no journal entries in " + ENTRIES.toAbsolutePath() + ": run runData");
        entries = new TreeMap<>();
        try (Stream<Path> files = Files.list(ENTRIES)) {
            for (Path p : files.filter(f -> f.toString().endsWith(".json")).toList()) {
                String id = p.getFileName().toString().replace(".json", "");
                var json = JsonParser.parseString(Files.readString(p));
                JournalEntry entry = JournalEntry.CODEC.parse(JsonOps.INSTANCE, json)
                        .getOrThrow(err -> new AssertionError(id + ": " + err));
                entries.put(id, entry);
            }
        }
        lang = JsonParser.parseString(Files.readString(LANG)).getAsJsonObject();
    }

    private static boolean hasLang(String key) {
        return lang.has(key) && !lang.get(key).getAsString().isBlank();
    }

    private static boolean itemKnown(ResourceLocation id) {
        if (id.getNamespace().equals("minecraft")) return true;
        return hasLang("item." + id.getNamespace() + "." + id.getPath()) || hasLang("block." + id.getNamespace() + "." + id.getPath());
    }

    private static boolean entityKnown(ResourceLocation id) {
        return id.getNamespace().equals("minecraft") || hasLang("entity." + id.getNamespace() + "." + id.getPath());
    }

    private static boolean recipeExists(ResourceLocation id) {
        String rel = "data/" + id.getNamespace() + "/recipe/" + id.getPath() + ".json";
        return Files.exists(MAIN.resolve(rel)) || Files.exists(GENERATED.resolve(rel));
    }

    private static boolean advancementExists(ResourceLocation id) {
        String rel = "data/" + id.getNamespace() + "/advancement/" + id.getPath() + ".json";
        return Files.exists(MAIN.resolve(rel)) || Files.exists(GENERATED.resolve(rel));
    }

    /** Problems with an unlock condition (and its nested options), described for the failure message. */
    private static void checkUnlock(String id, Unlock u, List<String> problems) {
        u.advancement().filter(a -> !advancementExists(a)).ifPresent(a -> problems.add(id + ": unknown advancement " + a));
        u.entity().filter(e -> !entityKnown(e)).ifPresent(e -> problems.add(id + ": unlock names unknown entity " + e));
        u.item().filter(i -> !itemKnown(i)).ifPresent(i -> problems.add(id + ": unlock names unknown item " + i));
        for (Unlock option : u.any()) checkUnlock(id, option, problems);
    }

    @Test
    void everyEntryParsesAndHasItsText() {
        assertFalse(entries.isEmpty());
        List<String> problems = new ArrayList<>();
        for (var e : entries.entrySet()) {
            String id = e.getKey();
            JournalEntry entry = e.getValue();
            if (!hasLang(JournalEntry.titleKey(ResourceLocation.fromNamespaceAndPath(NS, id)))) problems.add(id + ": no title");
            if (entry.blocks().isEmpty()) problems.add(id + ": no blocks");
            if (entry.blocks().stream().noneMatch(b -> b instanceof JournalBlock.Text)) problems.add(id + ": no text at all");
            if (!itemKnown(entry.icon())) problems.add(id + ": unknown icon " + entry.icon());
            entry.creature().filter(c -> !entityKnown(c)).ifPresent(c -> problems.add(id + ": unknown creature " + c));
            checkUnlock(id, entry.unlock(), problems);
            for (JournalBlock block : entry.blocks()) {
                Optional<String> caption = Optional.empty();
                switch (block) {
                    case JournalBlock.Text t -> {
                        if (!hasLang(t.text())) problems.add(id + ": missing text " + t.text());
                    }
                    case JournalBlock.Entity en -> {
                        if (!entityKnown(en.entity())) problems.add(id + ": unknown entity " + en.entity());
                        caption = en.caption();
                    }
                    case JournalBlock.Items it -> {
                        it.items().stream().filter(i -> !itemKnown(i)).forEach(i -> problems.add(id + ": unknown item " + i));
                        caption = it.caption();
                    }
                    case JournalBlock.Recipe r -> {
                        if (!recipeExists(r.recipe())) problems.add(id + ": unknown recipe " + r.recipe());
                        caption = r.caption();
                    }
                    case JournalBlock.Image im -> {
                        Path tex = MAIN.resolve("assets/" + im.texture().getNamespace() + "/" + im.texture().getPath());
                        if (!Files.exists(tex)) problems.add(id + ": missing picture " + im.texture());
                        caption = im.caption();
                    }
                }
                caption.filter(k -> !hasLang(k)).ifPresent(k -> problems.add(id + ": missing caption " + k));
            }
        }
        assertTrue(problems.isEmpty(), String.join("\n", problems));
    }

    @Test
    void theLinkedEntriesExist() {
        for (String id : REQUIRED) assertTrue(entries.containsKey(id), "missing required journal entry " + id);
        JournalEntry first = entries.get("family_business");
        assertTrue(first.unlock().always(), "the first page is always open");
        assertEquals(JournalChapter.BASICS, first.chapter());
        assertEquals(0, first.order());
    }

    @Test
    void noTwoEntriesShareAPlaceInAChapter() {
        Map<String, String> seen = new HashMap<>();
        for (var e : entries.entrySet()) {
            String slot = e.getValue().chapter().id() + "#" + e.getValue().order();
            String clash = seen.put(slot, e.getKey());
            assertTrue(clash == null, e.getKey() + " and " + clash + " share " + slot);
        }
    }

    @Test
    void everyCreatureHasItsBestiaryEntry() {
        Set<String> covered = new HashSet<>();
        for (JournalEntry e : entries.values()) {
            e.creature().filter(c -> c.getNamespace().equals(NS)).ifPresent(c -> covered.add(c.getPath()));
        }
        for (String mob : CREATURES) {
            assertTrue(hasLang("entity." + NS + "." + mob), "no such creature in the lang file: " + mob);
            assertTrue(covered.contains(mob), "no journal entry has creature " + NS + ":" + mob
                    + " (add one in datagen/journal; see CLAUDE.md)");
        }
    }

    @Test
    void everyBossHasItsPageAmongTheBosses() {
        for (BossProgression.Boss boss : BossProgression.Boss.values()) {
            ResourceLocation type = ResourceLocation.fromNamespaceAndPath(NS, boss.entity);
            assertTrue(CREATURES.contains(boss.entity), boss + " is missing from CREATURES");
            boolean found = entries.values().stream()
                    .anyMatch(e -> e.chapter() == JournalChapter.BOSSES && e.creature().filter(type::equals).isPresent());
            assertTrue(found, "no BOSSES entry has creature " + type);
        }
    }

    @Test
    void theOldFixedPagesAreGone() {
        List<String> left = lang.keySet().stream().filter(k -> k.startsWith("journal." + NS + ".page")).toList();
        assertTrue(left.isEmpty(), "old journal page keys still generated: " + left);
    }
}
