"""18x18 status-effect icons for the mod's mob effects (textures/mob_effect/<id>.png)."""

from common import art, save
from pixelkit import hexc

K = hexc("#1E1410")  # outline ink

ICONS = {
    # A devil's trap: a red ring around a pentagram.
    "trapped": ([
        "..................",
        "......kkkkkk......",
        "....kkrrrrrrkk....",
        "...krrkkkkkkrrk...",
        "..krkk..rr..kkrk..",
        "..krk...rr...krk..",
        ".krk...r..r...krk.",
        ".krrrrrrrrrrrrrrk.",
        ".krk.rr....rr.krk.",
        ".krk..rr..rr..krk.",
        ".krk...rrrr...krk.",
        ".krk..rr..rr..krk.",
        "..krkr......rkrk..",
        "..krkk......kkrk..",
        "...krrkkkkkkrrk...",
        "....kkrrrrrrkk....",
        "......kkkkkk......",
        "..................",
    ], {"k": K, "r": hexc("#B3261E")}),
    # Stunned: little stars wheeling round.
    "stunned": ([
        "..................",
        "........k.........",
        ".......kyk........",
        "...k..kyyyk..k....",
        "..kyk..kyk..kyk...",
        "...k....k....k....",
        "..................",
        "....kkkkkkkkkk....",
        "...kwwwwwwwwwwk...",
        "..kww........wwk..",
        "..kw..........wk..",
        "..kww........wwk..",
        "...kwwwwwwwwwwk...",
        "....kkkkkkkkkk....",
        "......k....k......",
        ".....kyk..kyk.....",
        "......k....k......",
        "..................",
    ], {"k": K, "y": hexc("#F2D35B"), "w": hexc("#E8D9A8")}),
    # Marked: a branded sigil scar.
    "marked": ([
        "..................",
        "..................",
        "....kkk....kkk....",
        "...kmmmk..kmmmk...",
        "...kmkmmkkmmkmk...",
        "....k.kmmmmk.k....",
        ".......kmmk.......",
        "......kmmmmk......",
        ".....kmmkkmmk.....",
        "....kmmk..kmmk....",
        "....kmk....kmk....",
        "....kmk....kmk....",
        "....kmmk..kmmk....",
        ".....kmmkkmmk.....",
        "......kmmmmk......",
        ".......kkkk.......",
        "..................",
        "..................",
    ], {"k": K, "m": hexc("#A33B4D")}),
    # Possessed: an eye gone all black.
    "possessed": ([
        "..................",
        "..................",
        "..................",
        "......kkkkkk......",
        "....kkssssssk.....",
        "...kssssssssskk...",
        "..ksskkkkkkkksk...",
        ".ksskbbbbbbbbksk..",
        ".kskbbbbgbbbbbksk.",
        ".kskbbbbbbbbbbksk.",
        ".ksskbbbbbbbbkssk.",
        "..ksskkkkkkkkssk..",
        "...kssssssssssk...",
        "....kkssssssskk...",
        "......kkkkkkk.....",
        "..................",
        "..................",
        "..................",
    ], {"k": K, "s": hexc("#D9B79A"), "b": hexc("#0B0B0E"), "g": hexc("#5A5A66")}),
    # Concealed: a hood with nothing inside.
    "concealed": ([
        "..................",
        "......kkkkkk......",
        ".....kggggggk.....",
        "....kggggggggk....",
        "...kgggkkkkgggk...",
        "...kggkddddkggk...",
        "..kggkddddddkggk..",
        "..kggkddddddkggk..",
        "..kggkddddddkggk..",
        "..kgggkddddkgggk..",
        "..kggggkddkggggk..",
        ".kgggggkddkgggggk.",
        ".kggggkddddkggggk.",
        ".kgggkddddddkgggk.",
        ".kggkddddddddkggk.",
        "kgggkddddddddkgggk",
        "kkkkkkkkkkkkkkkkkk",
        "..................",
    ], {"k": K, "g": hexc("#5A6A7A"), "d": hexc("#1B2128")}),
    # Second Sight: a wide pale eye with a bright pupil.
    "second_sight": ([
        "..................",
        "........w.........",
        "...w....w....w....",
        "....w.......w.....",
        "......kkkkkk......",
        "....kkwwwwwwkk....",
        "...kwwwkkkkwwwk...",
        "..kwwwkbbbbkwwwk..",
        ".kwwwkbbwwbbkwwwk.",
        ".kwwwkbbwwbbkwwwk.",
        "..kwwwkbbbbkwwwk..",
        "...kwwwkkkkwwwk...",
        "....kkwwwwwwkk....",
        "......kkkkkk......",
        "....w.......w.....",
        "...w....w....w....",
        "........w.........",
        "..................",
    ], {"k": K, "w": hexc("#BFE3FF"), "b": hexc("#3D7FB8")}),
    # Jinxed: a hex bag tied shut, with a crooked cross.
    "jinxed": ([
        "..................",
        ".......k...k......",
        "........k.k.......",
        ".........k........",
        "......kkkkkk......",
        ".......kssk.......",
        "......kppppk......",
        ".....kppppppk.....",
        "....kppkppkppk....",
        "...kpppkkkkpppk...",
        "...kppppkkppppk...",
        "...kppppkkppppk...",
        "...kpppkppkpppk...",
        "...kppppppppppk...",
        "....kppppppppk....",
        ".....kkkkkkkk.....",
        "..................",
        "..................",
    ], {"k": K, "p": hexc("#5B3A6E"), "s": hexc("#B59A6A")}),
    # Bleeding: a falling drop of blood.
    "bleeding": ([
        "..................",
        "........k.........",
        ".......krk........",
        ".......krk........",
        "......krrrk.......",
        "......krrrk.......",
        ".....krrrrrk......",
        "....krrrrrrrk.....",
        "....krrhrrrrk.....",
        "...krrhrrrrrrk....",
        "...krrhrrrrrrk....",
        "...krrrrrrrrrk....",
        "...krrrrrrrrdk....",
        "....krrrrrrdk.....",
        ".....kkddddk......",
        ".......kkkk.......",
        "..................",
        "..................",
    ], {"k": K, "r": hexc("#B3261E"), "h": hexc("#E2685E"), "d": hexc("#7A1410")}),
    # Soulless: a hollow heart, cracked through.
    "soulless": ([
        "..................",
        "..................",
        "...kkkk....kkkk...",
        "..kggggk..kggggk..",
        ".kggkkggkkggkkggk.",
        ".kgk..kggggk..kgk.",
        ".kgk...kggk...kgk.",
        ".kgk....kk.k..kgk.",
        ".kggk....kk..kggk.",
        "..kggk..kk..kggk..",
        "...kggk..k.kggk...",
        "....kggk..kggk....",
        ".....kggkkggk.....",
        "......kggggk......",
        ".......kggk.......",
        "........kk........",
        "..................",
        "..................",
    ], {"k": K, "g": hexc("#6E6E7A")}),
}


def generate():
    for name, (rows, pal) in ICONS.items():
        save(art(rows, pal), "mob_effect", name)


if __name__ == "__main__":
    generate()
