package org.papiricoh.supernaturalcraft.reward.colt;

/** Names of the Colt's animations, generated by tools/artgen/colt_art.py. */
public final class ColtAnimations {

    public static final String PREFIX = "animation.the_colt.";
    public static final String IDLE_COCKED = "idle_cocked", IDLE_UNCOCKED = "idle_uncocked";
    public static final String FIRE = "fire", FIRE_LAST = "fire_last", DRY_FIRE = "dry_fire";
    public static final String RELOAD = "reload_", RELOAD_ABORT = "reload_abort", INSPECT = "inspect", INSPECT_EMPTY = "inspect_empty";
    /** Bones the renderer poses itself; no animation may key them. */
    public static final String[] PROCEDURAL = {"cylinder", "chamber_", "round_", "muzzle_flash"};

    private ColtAnimations() {
    }

    public static String reload(int n) {
        return RELOAD + n;
    }

    /** Every triggerable animation, by its short name. */
    public static String[] triggerables(int capacity) {
        String[] out = new String[6 + capacity];
        out[0] = FIRE;
        out[1] = FIRE_LAST;
        out[2] = DRY_FIRE;
        out[3] = RELOAD_ABORT;
        out[4] = INSPECT;
        out[5] = INSPECT_EMPTY;
        for (int n = 1; n <= capacity; n++) out[5 + n] = reload(n);
        return out;
    }
}
