package org.papiricoh.supernaturalcraft.client.book;

import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.resources.ResourceLocation;
import org.papiricoh.supernaturalcraft.SupernaturalCraft;

/**
 * The Hunter's Book's textures, all generated by {@code tools/artgen/book_art.py}, and where each
 * sprite sits in {@code book_widgets.png}. The layout here and in the script must agree.
 */
public final class BookAtlas {

    /** The open book: 416×272 used of a 512×512 sheet. */
    public static final ResourceLocation SPREAD = SupernaturalCraft.asResource("textures/gui/book/book_spread.png");
    public static final int SPREAD_SHEET = 512;
    /** Every widget sprite: 256×256. */
    public static final ResourceLocation WIDGETS = SupernaturalCraft.asResource("textures/gui/book/book_widgets.png");
    /** Old map paper, tiling every 256 pixels: the roadmap's ground. */
    public static final ResourceLocation ROADMAP_PAPER = SupernaturalCraft.asResource("textures/gui/book/roadmap_paper.png");
    /** Greyscale sparks, rings and glows for the spell preview, tinted when drawn: 64×64. */
    public static final ResourceLocation SPELL_FX = SupernaturalCraft.asResource("textures/gui/book/spell_fx.png");

    public record Sprite(ResourceLocation texture, int u, int v, int w, int h, int sheet) {
        public void draw(GuiGraphics g, int x, int y) {
            g.blit(texture, x, y, u, v, w, h, sheet, sheet);
        }

        /** Stretched to w×h (for nine-slices use {@link BookAtlas#panel}). */
        public void draw(GuiGraphics g, int x, int y, int w, int h) {
            g.blit(texture, x, y, w, h, u, v, this.w, this.h, sheet, sheet);
        }
    }

    private static Sprite w(int u, int v, int width, int height) {
        return new Sprite(WIDGETS, u, v, width, height, 256);
    }

    private static Sprite fx(int u, int v, int width, int height) {
        return new Sprite(SPELL_FX, u, v, width, height, 64);
    }

    // --- tabs: 30×22, one column per section (home, journal, scriptorium, roadmap) ------------------
    public static final int TAB_W = 30, TAB_H = 22;

    public static Sprite tab(int section, boolean active) {
        return w(section * TAB_W, active ? TAB_H : 0, TAB_W, TAB_H);
    }

    // --- page turning and marks ------------------------------------------------------------------------
    public static final Sprite ARROW_PREV = w(0, 44, 18, 12), ARROW_PREV_HOVER = w(18, 44, 18, 12);
    public static final Sprite ARROW_NEXT = w(36, 44, 18, 12), ARROW_NEXT_HOVER = w(54, 44, 18, 12);
    /** A bookmark ribbon, 10×24: unmarked (an outline) and marked (red silk). */
    public static final Sprite RIBBON_OFF = w(72, 44, 10, 24), RIBBON_ON = w(82, 44, 10, 24);
    /** 6×6 dots: gold for unread, red for a warning. */
    public static final Sprite DOT_GOLD = w(92, 44, 6, 6), DOT_RED = w(98, 44, 6, 6);

    // --- roadmap nodes: boss 32×32 and milestone 24×24, in three states (done, available, locked) ------
    public static Sprite bossFrame(int state) {
        return w(state * 32, 72, 32, 32);
    }

    public static Sprite stepFrame(int state) {
        return w(96 + state * 24, 72, 24, 24);
    }

    public static final Sprite SEAL = w(168, 72, 12, 12), LOCK = w(180, 72, 10, 12);

    // --- slots ---------------------------------------------------------------------------------------
    public static final Sprite SIGIL_SLOT = w(0, 104, 20, 20), SIGIL_SLOT_HOVER = w(20, 104, 20, 20);
    public static final Sprite LIBRARY_SLOT = w(40, 104, 56, 20), LIBRARY_SLOT_HOVER = w(96, 104, 56, 20);

    // --- nine-slices (4 px border): a card 32×32, a button 32×16 in three states ---------------------
    public static final Sprite CARD = w(0, 128, 32, 32);
    public static final Sprite BUTTON = w(32, 128, 32, 16), BUTTON_HOVER = w(32, 144, 32, 16), BUTTON_OFF = w(32, 160, 32, 16);

    // --- bars: a 64×8 frame and 64×8 fills (mana, sanity, danger) -------------------------------------
    public static final Sprite BAR_FRAME = w(64, 128, 64, 8);
    public static final Sprite BAR_MANA = w(64, 136, 64, 8), BAR_SANITY = w(64, 144, 64, 8), BAR_DANGER = w(64, 152, 64, 8);

    // --- ornaments -----------------------------------------------------------------------------------
    public static final Sprite CORNER = w(128, 128, 16, 16);
    /** An inked flourish under a heading, 120×8. */
    public static final Sprite FLOURISH = w(0, 192, 120, 8);

    // --- spell preview (greyscale, tint with setShaderColor) ------------------------------------------
    public static final Sprite FX_SPARK = fx(0, 0, 8, 8), FX_GLOW = fx(32, 0, 16, 16);
    public static final Sprite FX_RING = fx(0, 16, 32, 32), FX_STREAK = fx(32, 16, 32, 8);

    private BookAtlas() {
    }

    /** Draws a nine-slice sprite with a 4 px border stretched to w×h. */
    public static void panel(GuiGraphics g, Sprite s, int x, int y, int w, int h) {
        int b = 4, mw = s.w() - 2 * b, mh = s.h() - 2 * b;
        int iw = Math.max(0, w - 2 * b), ih = Math.max(0, h - 2 * b);
        ResourceLocation t = s.texture();
        int u = s.u(), v = s.v(), sh = s.sheet();
        // corners
        g.blit(t, x, y, u, v, b, b, sh, sh);
        g.blit(t, x + w - b, y, u + s.w() - b, v, b, b, sh, sh);
        g.blit(t, x, y + h - b, u, v + s.h() - b, b, b, sh, sh);
        g.blit(t, x + w - b, y + h - b, u + s.w() - b, v + s.h() - b, b, b, sh, sh);
        // edges and middle, stretched
        g.blit(t, x + b, y, iw, b, u + b, v, mw, b, sh, sh);
        g.blit(t, x + b, y + h - b, iw, b, u + b, v + s.h() - b, mw, b, sh, sh);
        g.blit(t, x, y + b, b, ih, u, v + b, b, mh, sh, sh);
        g.blit(t, x + w - b, y + b, b, ih, u + s.w() - b, v + b, b, mh, sh, sh);
        g.blit(t, x + b, y + b, iw, ih, u + b, v + b, mw, mh, sh, sh);
    }
}
