package org.papiricoh.supernaturalcraft.client.book;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.mojang.logging.LogUtils;
import com.mojang.serialization.JsonOps;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.packs.resources.ResourceManager;
import net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener;
import net.minecraft.util.profiling.ProfilerFiller;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.RegisterClientReloadListenersEvent;
import org.papiricoh.supernaturalcraft.SupernaturalCraft;
import org.papiricoh.supernaturalcraft.journal.JournalChapter;
import org.papiricoh.supernaturalcraft.journal.JournalEntry;
import org.papiricoh.supernaturalcraft.journal.Roadmap;
import org.papiricoh.supernaturalcraft.journal.RoadmapNode;
import org.slf4j.Logger;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The journal's entries ({@code assets/<ns>/journal/entries/*.json}) and the roadmap's roads
 * ({@code assets/<ns>/journal/roadmaps/*.json}), loaded with the resource packs. Generated by
 * {@code datagen/journal}; a resource pack may add or replace them.
 */
@EventBusSubscriber(modid = SupernaturalCraft.MODID, value = Dist.CLIENT)
public final class BookData extends SimpleJsonResourceReloadListener {

    private static final Logger LOGGER = LogUtils.getLogger();
    private static final String ENTRIES = "entries/";
    private static final String ROADS = "roadmaps/";

    private static Map<ResourceLocation, JournalEntry> entries = Map.of();
    private static Map<ResourceLocation, Roadmap> roads = Map.of();

    private BookData() {
        super(new Gson(), "journal");
    }

    @SubscribeEvent
    public static void register(RegisterClientReloadListenersEvent event) {
        event.registerReloadListener(new BookData());
    }

    @Override
    protected void apply(Map<ResourceLocation, JsonElement> files, ResourceManager manager, ProfilerFiller profiler) {
        List<Map.Entry<ResourceLocation, JournalEntry>> found = new ArrayList<>();
        List<Map.Entry<ResourceLocation, Roadmap>> foundRoads = new ArrayList<>();
        files.forEach((file, json) -> {
            if (file.getPath().startsWith(ENTRIES)) {
                ResourceLocation id = file.withPath(file.getPath().substring(ENTRIES.length()));
                JournalEntry.CODEC.parse(JsonOps.INSTANCE, json)
                        .resultOrPartial(e -> LOGGER.error("Bad journal entry {}: {}", file, e))
                        .ifPresent(entry -> found.add(Map.entry(id, entry)));
            } else if (file.getPath().startsWith(ROADS)) {
                ResourceLocation id = file.withPath(file.getPath().substring(ROADS.length()));
                Roadmap.CODEC.parse(JsonOps.INSTANCE, json)
                        .resultOrPartial(e -> LOGGER.error("Bad roadmap {}: {}", file, e))
                        .ifPresent(road -> foundRoads.add(Map.entry(id, road)));
            }
        });
        found.sort(Comparator.<Map.Entry<ResourceLocation, JournalEntry>>comparingInt(e -> e.getValue().chapter().ordinal())
                .thenComparingInt(e -> e.getValue().order()).thenComparing(e -> e.getKey().toString()));
        Map<ResourceLocation, JournalEntry> sorted = new LinkedHashMap<>();
        found.forEach(e -> sorted.put(e.getKey(), e.getValue()));
        entries = sorted;
        foundRoads.sort(Comparator.<Map.Entry<ResourceLocation, Roadmap>>comparingInt(e -> e.getValue().order())
                .thenComparing(e -> e.getKey().toString()));
        Map<ResourceLocation, Roadmap> sortedRoads = new LinkedHashMap<>();
        foundRoads.forEach(e -> sortedRoads.put(e.getKey(), e.getValue()));
        roads = sortedRoads;
    }

    /** Every entry, in index order (chapter, then order, then id). */
    public static Map<ResourceLocation, JournalEntry> entries() {
        return entries;
    }

    public static List<Map.Entry<ResourceLocation, JournalEntry>> chapter(JournalChapter chapter) {
        return entries.entrySet().stream().filter(e -> e.getValue().chapter() == chapter).toList();
    }

    /** Every road of the roadmap, in menu order. */
    public static Map<ResourceLocation, Roadmap> roads() {
        return roads;
    }

    /** One road's nodes (empty if there is no such road). */
    public static List<RoadmapNode> roadmap(ResourceLocation road) {
        Roadmap r = roads.get(road);
        return r == null ? List.of() : r.nodes();
    }

    /** The road to the Cage: the main road, the one the dashboard follows. */
    public static List<RoadmapNode> roadmap() {
        return roadmap(Roadmap.CAGE);
    }

    /** The road a node belongs to, or null. */
    public static ResourceLocation roadOf(String nodeId) {
        for (var e : roads.entrySet()) {
            if (e.getValue().nodes().stream().anyMatch(n -> n.id().equals(nodeId))) return e.getKey();
        }
        return null;
    }
}
